one store sold 10 goods during opening(opening event)
with error

Traceback (most recent call last):
  File "D:/__DOCS_PROJECTS/_GIT/ITEA/lesson_02/lesson_02_task_02.py", line 40, in <module>
    Shop.get_all_sold_goods()
TypeError: get_all_sold_goods() missing 1 required positional argument: 'self'